---
title: "Reading Data From the Web"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```


## Scrape a Table from a website 

I want the first table from [this page](https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

extract the table(s); focus on the first one 

```{r}
tabl_marj =  
  drug_use_html %>% 
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```


## Star Wars Movie info

I want the data from [here](https://www.imdb.com/list/ls070150896/).

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```


Grab elements that we want

```{r}
titles_vec = 
  swm_html %>% 
  html_nodes(css = ".ipc-title__text--reduced") %>% 
  html_text()

run_time_vec =
  swm_html %>% 
  html_nodes(css = ".dli-title-metadata-item:nth-child(2)") %>% 
  html_text()
```
 
##Get some water Data

API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")

nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |> 
  content("text") |>
  jsonlite::fromJSON() |>
  as_tibble()
```



